// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/1.0/booking": {
            "get": {
                "description": "Get All Booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Get All Booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/booking.Booking"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Create Booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Booking",
                        "name": "CreateBooking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/booking.RequestCreateBookingSwagger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Booking",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/booking/admin": {
            "get": {
                "description": "Get All Booking on Hotel harus admin hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Get All Booking on Hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/booking.Booking"
                        }
                    }
                }
            }
        },
        "/1.0/booking/proses-reservasi": {
            "patch": {
                "description": "Update Booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Update Booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Update Booking",
                        "name": "UpdateBooking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/booking.RequestUpdateBooking"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Booking",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/booking/{id}": {
            "get": {
                "description": "Get Booking By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking"
                ],
                "summary": "Get Booking By Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Booking ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/booking.Booking"
                        }
                    }
                }
            }
        },
        "/1.0/fasilitas": {
            "get": {
                "description": "Get All Fasilitas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Get All Fasilitas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fasilitas.Fasilitas"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Fasilitas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Create Fasilitas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Fasilitas",
                        "name": "CreateFasilitas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fasilitas.RequestFasilitas"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Fasilitas",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/fasilitas-hotel": {
            "get": {
                "description": "Get All Fasilitas Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas Hotel"
                ],
                "summary": "Get All Fasilitas Hotel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fasilitashotel.ResponseFasilitasHotel"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Fasilitas Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas Hotel"
                ],
                "summary": "Create Fasilitas Hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Fasilitas Hotel",
                        "name": "CreateFasilitasHotel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fasilitashotel.RequestFasilitasHotel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Fasilitas Hotel",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/fasilitas-hotel/by-fasilitas/{id}": {
            "get": {
                "description": "Get Fasilitas By Fasilitas Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas Hotel"
                ],
                "summary": "Get Fasilitas By Fasilitas Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fasilitas ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fasilitashotel.ResponseFasilitasHotel"
                        }
                    }
                }
            }
        },
        "/1.0/fasilitas-hotel/by-hotel/{id}": {
            "get": {
                "description": "Get Fasilitas By Hotel Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas Hotel"
                ],
                "summary": "Get Fasilitas By Hotel Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fasilitashotel.ResponseFasilitasHotel"
                        }
                    }
                }
            }
        },
        "/1.0/fasilitas-hotel/{id}": {
            "get": {
                "description": "Get Fasilitas Hotel By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas Hotel"
                ],
                "summary": "Get Fasilitas Hotel By Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fasilitas Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fasilitashotel.ResponseFasilitasHotel"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Fasilitas Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas Hotel"
                ],
                "summary": "Update Fasilitas Hotel",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fasilitas Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Update Fasilitas Hotel",
                        "name": "UpdateFasilitasHotel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fasilitashotel.RequestFasilitasHotel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Fasilitas Hotel",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Fasilitas Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas Hotel"
                ],
                "summary": "Delete Fasilitas Hotel",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fasilitas Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Fasilitas Hotel",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/fasilitas/{id}": {
            "get": {
                "description": "Get Fasilitas By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Get Fasilitas By Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fasilitas ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fasilitas.Fasilitas"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Fasilitas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Update Fasilitas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fasilitas ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Update Fasilitas",
                        "name": "UpdateFasilitas",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fasilitas.RequestFasilitas"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Fasilitas",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Fasilitas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fasilitas"
                ],
                "summary": "Delete Fasilitas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Fasilitas ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Fasilitas",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/hak-akses": {
            "get": {
                "description": "Get All Hak Akses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hak Akses"
                ],
                "summary": "Get All Hak Akses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hakakses.HakAkses"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Hak Akses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hak Akses"
                ],
                "summary": "Create Hak Akses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Hak Akses",
                        "name": "CreateHakAkses",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hakakses.RequestHakAkses"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Hak Akses",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/hak-akses/{id}": {
            "get": {
                "description": "Get Hak Akses By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hak Akses"
                ],
                "summary": "Get Hak Akses By Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hak Akses ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hakakses.HakAkses"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Hak Akses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hak Akses"
                ],
                "summary": "Update Hak Akses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hak Akses ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Update Hak Akses",
                        "name": "UpdateHakAkses",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hakakses.RequestHakAkses"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Hak Akses",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Hak Akses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hak Akses"
                ],
                "summary": "Delete Hak Akses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hak Akses ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Hak Akses",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/hotel": {
            "get": {
                "description": "Get All Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Get All Hotel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel.Hotel"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Create Hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Hotel",
                        "name": "CreateHotel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel.RequestHotel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Hotel",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/hotel/{id}": {
            "get": {
                "description": "Get Hotel By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Get Hotel By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel.Hotel"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Update Hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Hotel",
                        "name": "UpdateHotel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hotel.RequestHotel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Hotel",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hotel"
                ],
                "summary": "Delete Hotel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Hotel",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/kamar": {
            "get": {
                "description": "Get All Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kamar"
                ],
                "summary": "Get All Kamar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kamar.Kamar"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kamar"
                ],
                "summary": "Create Kamar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Kamar",
                        "name": "CreateKamar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kamar.RequestKamar"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/kamar/{id}": {
            "get": {
                "description": "Get Kamar By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kamar"
                ],
                "summary": "Get Kamar By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kamar ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/kamar.Kamar"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kamar"
                ],
                "summary": "Update Kamar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kamar ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Update Kamar",
                        "name": "UpdateKamar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/kamar.RequestKamar"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kamar"
                ],
                "summary": "Delete Kamar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Kamar ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/login": {
            "post": {
                "description": "Login User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login",
                        "name": "Login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RequestLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Login",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Logout User",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Logout User",
                "responses": {
                    "200": {
                        "description": "Success Logout",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/pembayaran": {
            "get": {
                "description": "Get All Pembayaran",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pembayaran"
                ],
                "summary": "Get All Pembayaran",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pembayaran.ResponsePembayaran"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Pembayaran",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pembayaran"
                ],
                "summary": "Create Pembayaran",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Pembayaran",
                        "name": "CreatePembayaran",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pembayaran.RequestPembayaran"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Pembayaran",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/pembayaran/{id}": {
            "get": {
                "description": "Get Pembayaran By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pembayaran"
                ],
                "summary": "Get Pembayaran By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Pembayaran",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pembayaran.ResponsePembayaran"
                        }
                    }
                }
            }
        },
        "/1.0/register": {
            "post": {
                "description": "Create User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "Register",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RequestCreateUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create User",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/register-admin-hotel": {
            "post": {
                "description": "Create Admin Hotel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create Admin Hotel",
                "parameters": [
                    {
                        "description": "Register",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RequestCreateAdminHotel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create User",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/status-booking": {
            "get": {
                "description": "Get All Status Booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Booking"
                ],
                "summary": "Get All Status Booking",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/statusbooking.StatusBooking"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Status Booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Booking"
                ],
                "summary": "Create Status Booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Status Booking",
                        "name": "CreateStatusBooking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/statusbooking.RequestStatusBooking"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Status Booking",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/status-booking/{id}": {
            "get": {
                "description": "Get Status Booking By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Booking"
                ],
                "summary": "Get Status Booking By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Status Booking",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/statusbooking.StatusBooking"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Status Booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Booking"
                ],
                "summary": "Update Status Booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Status Booking",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Status Booking",
                        "name": "UpdateStatusBooking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/statusbooking.RequestStatusBooking"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Status Booking",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Status Booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Booking"
                ],
                "summary": "Delete Status Booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Status Booking",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Status Booking",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/status-kamar": {
            "get": {
                "description": "Get All Status Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Kamar"
                ],
                "summary": "Get All Status Kamar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/statuskamar.StatusKamar"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Status Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Kamar"
                ],
                "summary": "Create Status Kamar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Status Kamar",
                        "name": "CreateStatusKamar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/statuskamar.RequestStatusKamar"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Status Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/status-kamar/{id}": {
            "get": {
                "description": "Get Status Kamar By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Kamar"
                ],
                "summary": "Get Status Kamar By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Status Kamar ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/statuskamar.StatusKamar"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Status Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Kamar"
                ],
                "summary": "Update Status Kamar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Status Kamar ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Status Kamar",
                        "name": "UpdateStatusKamar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/statuskamar.RequestStatusKamar"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Status Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Status Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status Kamar"
                ],
                "summary": "Delete Status Kamar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Status Kamar ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Status Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/tipe-kamar": {
            "get": {
                "description": "Get All Tipe Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipe Kamar"
                ],
                "summary": "Get All Tipe Kamar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tipekamar.TipeKamar"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Tipe Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipe Kamar"
                ],
                "summary": "Create Tipe Kamar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create Tipe Kamar",
                        "name": "CreateTipeKamar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tipekamar.RequestTipeKamar"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success Create Tipe Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/1.0/tipe-kamar/{id}": {
            "get": {
                "description": "Get Tipe Kamar By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipe Kamar"
                ],
                "summary": "Get Tipe Kamar By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Tipe Kamar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tipekamar.TipeKamar"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Tipe Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipe Kamar"
                ],
                "summary": "Update Tipe Kamar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Tipe Kamar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Tipe Kamar",
                        "name": "UpdateTipeKamar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tipekamar.RequestTipeKamar"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Update Tipe Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Tipe Kamar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipe Kamar"
                ],
                "summary": "Delete Tipe Kamar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID Tipe Kamar",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Tipe Kamar",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "booking.Booking": {
            "type": "object",
            "required": [
                "hotel_id",
                "kamar_id",
                "status_booking_id",
                "total_biaya",
                "user_id"
            ],
            "properties": {
                "booking_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "hotel_id": {
                    "type": "integer"
                },
                "jumlah_hari": {
                    "type": "integer"
                },
                "kamar_id": {
                    "type": "integer"
                },
                "status_booking": {
                    "$ref": "#/definitions/statusbooking.StatusBooking"
                },
                "status_booking_id": {
                    "type": "integer"
                },
                "tanggal_check_in": {
                    "type": "string"
                },
                "tanggal_check_out": {
                    "type": "string"
                },
                "total_biaya": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "booking.RequestCreateBookingSwagger": {
            "type": "object",
            "required": [
                "kamar_id"
            ],
            "properties": {
                "kamar_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "booking.RequestUpdateBooking": {
            "type": "object",
            "required": [
                "booking_id",
                "kamar_id",
                "status_booking_id"
            ],
            "properties": {
                "booking_id": {
                    "type": "integer"
                },
                "kamar_id": {
                    "type": "integer"
                },
                "status_booking_id": {
                    "type": "integer"
                }
            }
        },
        "fasilitas.Fasilitas": {
            "type": "object",
            "required": [
                "deskripsi",
                "jenis_fasilitas"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deskripsi": {
                    "type": "string",
                    "minLength": 10
                },
                "fasilitas_id": {
                    "type": "integer"
                },
                "jenis_fasilitas": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "fasilitas.RequestFasilitas": {
            "type": "object",
            "required": [
                "deskripsi",
                "jenis_fasilitas"
            ],
            "properties": {
                "deskripsi": {
                    "type": "string",
                    "minLength": 10
                },
                "jenis_fasilitas": {
                    "type": "string"
                }
            }
        },
        "fasilitashotel.RequestFasilitasHotel": {
            "type": "object",
            "required": [
                "fasilitas_id",
                "hotel_id"
            ],
            "properties": {
                "fasilitas_id": {
                    "type": "integer"
                },
                "hotel_id": {
                    "type": "integer"
                }
            }
        },
        "fasilitashotel.ResponseFasilitasHotel": {
            "type": "object",
            "required": [
                "fasilitas_id",
                "hotel_id"
            ],
            "properties": {
                "fasilitas": {
                    "$ref": "#/definitions/fasilitas.Fasilitas"
                },
                "fasilitas_hotel_id": {
                    "type": "integer"
                },
                "fasilitas_id": {
                    "type": "integer"
                },
                "hotel": {
                    "$ref": "#/definitions/hotel.Hotel"
                },
                "hotel_id": {
                    "type": "integer"
                }
            }
        },
        "hakakses.HakAkses": {
            "type": "object",
            "required": [
                "hak_akses"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "hak_akses": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "hak_akses_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hakakses.RequestHakAkses": {
            "type": "object",
            "required": [
                "hak_akses"
            ],
            "properties": {
                "hak_akses": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "hotel.Hotel": {
            "type": "object",
            "required": [
                "alamat_hotel",
                "email_hotel",
                "nama_hotel",
                "telp_hotel"
            ],
            "properties": {
                "alamat_hotel": {
                    "type": "string",
                    "minLength": 10
                },
                "created_at": {
                    "type": "string"
                },
                "email_hotel": {
                    "type": "string"
                },
                "hotel_id": {
                    "type": "integer"
                },
                "nama_hotel": {
                    "type": "string",
                    "minLength": 3
                },
                "telp_hotel": {
                    "type": "string",
                    "minLength": 10
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hotel.RequestHotel": {
            "type": "object",
            "required": [
                "alamat_hotel",
                "email_hotel",
                "nama_hotel",
                "telp_hotel"
            ],
            "properties": {
                "alamat_hotel": {
                    "type": "string",
                    "minLength": 10
                },
                "email_hotel": {
                    "type": "string"
                },
                "nama_hotel": {
                    "type": "string",
                    "minLength": 3
                },
                "telp_hotel": {
                    "type": "string",
                    "minLength": 10
                }
            }
        },
        "kamar.Kamar": {
            "type": "object",
            "required": [
                "harga",
                "nomor_kamar",
                "tipe_kamar_id"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "harga": {
                    "type": "integer"
                },
                "hotel_id": {
                    "type": "integer"
                },
                "kamar_id": {
                    "type": "integer"
                },
                "nomor_kamar": {
                    "type": "string"
                },
                "status_kamar": {
                    "$ref": "#/definitions/statuskamar.StatusKamar"
                },
                "status_kamar_id": {
                    "type": "integer"
                },
                "tipe_kamar_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "kamar.RequestKamar": {
            "type": "object",
            "required": [
                "harga",
                "hotel_id",
                "nomor_kamar",
                "tipe_kamar_id"
            ],
            "properties": {
                "harga": {
                    "type": "integer"
                },
                "hotel_id": {
                    "type": "integer"
                },
                "nomor_kamar": {
                    "type": "string"
                },
                "status_kamar_id": {
                    "type": "integer"
                },
                "tipe_kamar_id": {
                    "type": "integer"
                }
            }
        },
        "pembayaran.RequestPembayaran": {
            "type": "object",
            "required": [
                "booking_id",
                "total_pembayaran"
            ],
            "properties": {
                "booking_id": {
                    "type": "integer"
                },
                "total_pembayaran": {
                    "type": "integer"
                }
            }
        },
        "pembayaran.ResponsePembayaran": {
            "type": "object",
            "required": [
                "booking_id",
                "total_pembayaran"
            ],
            "properties": {
                "booking": {
                    "$ref": "#/definitions/booking.Booking"
                },
                "booking_id": {
                    "type": "integer"
                },
                "pembayaran_id": {
                    "type": "integer"
                },
                "tanggal_pembayaran": {
                    "type": "string"
                },
                "total_pembayaran": {
                    "type": "integer"
                }
            }
        },
        "statusbooking.RequestStatusBooking": {
            "type": "object",
            "required": [
                "status_booking_nama"
            ],
            "properties": {
                "status_booking_nama": {
                    "type": "string"
                }
            }
        },
        "statusbooking.StatusBooking": {
            "type": "object",
            "required": [
                "status_booking_nama"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "status_booking_id": {
                    "type": "integer"
                },
                "status_booking_nama": {
                    "type": "string",
                    "minLength": 3
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "statuskamar.RequestStatusKamar": {
            "type": "object",
            "required": [
                "status_kamar_nama"
            ],
            "properties": {
                "status_kamar_nama": {
                    "type": "string"
                }
            }
        },
        "statuskamar.StatusKamar": {
            "type": "object",
            "required": [
                "status_kamar_nama"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "status_kamar_id": {
                    "type": "integer"
                },
                "status_kamar_nama": {
                    "type": "string",
                    "minLength": 3
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "tipekamar.RequestTipeKamar": {
            "type": "object",
            "required": [
                "tipe_kamar_nama"
            ],
            "properties": {
                "tipe_kamar_nama": {
                    "type": "string"
                }
            }
        },
        "tipekamar.TipeKamar": {
            "type": "object",
            "required": [
                "tipe_kamar_nama"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "tipe_kamar_id": {
                    "type": "integer"
                },
                "tipe_kamar_nama": {
                    "type": "string",
                    "minLength": 3
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "user.RequestCreateAdminHotel": {
            "type": "object",
            "required": [
                "email",
                "hotel_id",
                "nama",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "hotel_id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string",
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "user.RequestCreateUser": {
            "type": "object",
            "required": [
                "email",
                "nama",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nama": {
                    "type": "string",
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "user.RequestLogin": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Reservasi Hotel API",
	Description:      "API untuk reservasi hotel\nTo access the API, you need to register and login first",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
